### ISSUE TITLE
Decorator for action logger

### ISSUE THREAD

**Issue by ritz078** [kadirahq/storybook-ui#14]
Currently, if there is one object in the array its printed as 

```
[Object]
```
Which isn't useful but is standard. It is of no use until we expand it. I initially thought that in case there is an array of length 1, then show the first element, but it will be wrong anyways as not everyone will be happy with that. Can there be a way where we can customize what we want to log ? Like in this case, i would like to log `Array[0]` that would make more sense for me.

In simple words, I want to customize the data shown in the logger according to my needs so just like a decorator, I would like to have a decorator for logger data. 

Also there we can set whether we want to show non-enumerables in the log or not.

**Comment by mnmtanish** [comment]
Pull request opened here https://github.com/kadirahq/storybook-addon-actions/pull/3.
