### ISSUE TITLE
Tabs in action logger

### ISSUE THREAD

**Issue by ritz078** [kadirahq/storybook-ui#19]
It will be great if there can be API to add tabs in action logger and plugins can be made for that like props info etc.

**Comment by arunoda** [comment]
Yeah. This is pretty useful.
I am looking at few ways to do that.
Any ideas.

If that's the case, we could implement the action logger also via that API.
It's come with default but, allow to support others too.

**Comment by mnmtanish** [comment]
Fixed with v3.0.0
