### ISSUE TITLE
Error in running the example app

### ISSUE THREAD

**Issue by ritz078** [kadirahq/storybook-ui#6]
Doesn't work following the steps given in the doc. First shows that react-hot-loader and babel are missing then after install them it shows that 
```
The node API for `babel` has been moved to `babel-core`
```

**Comment by arunoda** [comment]
Really. I will give a try. May be I am missing some modules.

**Comment by arunoda** [comment]
@ritz078 Try now. Just fixed the issue.
See: b94b494e79ab36a43591e6f7699c136ad7c4f125

**Comment by ritz078** [comment]
still doesn't work.

<img width="776" alt="screen shot 2016-06-24 at 1 40 31 am" src="https://cloud.githubusercontent.com/assets/5389035/16318406/b7f58f0e-39ac-11e6-8674-f133292de7e3.png">

**Comment by arunoda** [comment]
Have you run npm install on the main repo? I mean ../example repo?

**Comment by arunoda** [comment]
Hope you are using NPM3 :)

**Comment by ritz078** [comment]
I wasn't using npm@3. This should be mentioned in Readme.
