### ISSUE TITLE
Request: Option to hide action logger

### ISSUE THREAD

**Issue by kevinSuttle** [kadirahq/storybook-ui#9]

**Comment by arunoda** [comment]
Yes. This would be cool to have. 
Basically, this can be implemented with query params for now as well.

You need to simply add these query params: `full=0&down=0&left=1`.

We could do this by while configuring the UI as well. If so, are we going to close Action logger forever or allow to show it back?

**Comment by kevinSuttle** [comment]
Good question. I think collapsible would be nice.

**Comment by arunoda** [comment]
Okay. Then we could add above queryParams by default or set the default option to hide if there is no query param.

**Comment by mnmtanish** [comment]
This can be fixed with #41 and https://github.com/kadirahq/storybook-addon-options
It'll work from Storybook `v2.19.0`
